name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Linter
      run: flake8 --format=html --htmldir=flake8-report
      continue-on-error: true  

    - name: Upload Flake8 Report
      if: always()  
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake8-report
